twig:
    default_path: '%kernel.project_dir%/templates'
    paths :
         '%kernel.project_dir%/public/css/css_site/images': images
         '%kernel.project_dir%/assets/css': css
         '%kernel.project_dir%/public/css/css_site/css': style
    